name: Hello CI

on:
 push:

jobs:
   say-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Greet
         run: echo "Hello from Github Actions"

       - name:  ask
         run: echo "How are you"

       - name: tell
         run: echo "you gone get what you want"
     
